/// Flutter icons MoovbeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoovbeIcons
///      fonts:
///       - asset: fonts/MoovbeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MoovbeIcons {
  MoovbeIcons._();

  static const _kFontFam = 'MoovbeIcons';
  static const String? _kFontPkg = null;

  static const IconData seat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
